### ISSUE TITLE
Is rst2pdf incompatible with Python 3.X?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [conda-forge/rst2pdf-feedstock#8]
When I try to install rst2pdf, I get a message informing me that rst2pdf is incompatible with Python 3.X.  But, other information about rst2pdf contradicts this.  I'm hoping for clarification.

(py38) >conda install rst2pdf
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__cuda==8.0=0: 100%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 3/3 [00:00<00:00,  4.21it/s]-failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - rst2pdf -> python[version='<3']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/win-64::__cuda==8.0=0
  - feature:|@/win-64::__cuda==8.0=0

Your installed version is: 8.0

**Comment by chrisburr** [comment]
This is now working, it turned out to be a issue with a `smartypants` update having not been made correctly causing `rst2pdf` to be unusable.

Thanks for reporting and sorry for the delay in getting it fixed :)
